# Generated by Django 2.1.7 on 2019-03-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petspace', '0002_auto_20190314_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='qr_code',
            field=models.CharField(default='', max_length=100),
        ),
    ]
