# Generated by Django 2.1.7 on 2019-03-15 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petspace', '0003_pet_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='qr_code',
        ),
    ]
