# Generated by Django 2.1.7 on 2019-03-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petspace', '0004_remove_pet_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='lost',
            field=models.BooleanField(default=False),
        ),
    ]
